# Generated by Django 3.2.25 on 2025-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husbent_name', models.CharField(max_length=150)),
                ('husbent_age', models.CharField(max_length=150)),
                ('h_aadhar_number', models.CharField(max_length=150)),
                ('husbent_job', models.CharField(max_length=150)),
                ('consult_hospital', models.CharField(max_length=150)),
                ('wardname', models.CharField(max_length=150)),
                ('wardnumber', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aser', models.CharField(max_length=150)),
                ('ains', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='pregregisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('con_date', models.CharField(max_length=150)),
                ('last_periods_date', models.CharField(max_length=150)),
                ('blood_group', models.CharField(max_length=150)),
                ('weight', models.CharField(max_length=150)),
                ('height', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('last_checkup_date', models.CharField(max_length=150)),
                ('disease', models.CharField(max_length=150)),
                ('husbands_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('question', models.CharField(max_length=150)),
                ('reply', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('ward_number', models.CharField(max_length=150)),
                ('work_place', models.CharField(max_length=150)),
                ('panchayat', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('no_pregnent_womens', models.CharField(max_length=150)),
                ('no_vacination_child', models.CharField(max_length=150)),
                ('ward_no', models.CharField(max_length=150)),
                ('panchayat', models.CharField(max_length=150)),
                ('aid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='userregisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('ward_no', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('aadhar_number', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('child_name', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=150)),
                ('ward_no', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('vaccine_details', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('aid', models.CharField(max_length=150)),
            ],
        ),
    ]
